# Generated by Django 3.1.7 on 2021-04-13 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(default='user1', max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dob', models.DateTimeField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('date_of_joining', models.DateTimeField(default=django.utils.timezone.now)),
                ('prof_pic', models.ImageField(null=True, upload_to='prof_pics')),
                ('bio', models.CharField(default='Welcome to SU-Learn', max_length=180)),
                ('following', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(default='user1', max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('date_of_joining', models.DateTimeField(default=django.utils.timezone.now)),
                ('educational_qualifications', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('prof_pic', models.ImageField(upload_to='prof_pics')),
                ('bio', models.CharField(default='Welcome to SU-Learn', max_length=180)),
                ('followers', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
