# Generated by Django 3.1.7 on 2021-04-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210413_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='prof_pics'),
        ),
    ]
